### ISSUE TITLE
TypeError: 'str' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by bilaleknc** [jvcss/PyInstallerStreamlit#6]
![image](https://github.com/user-attachments/assets/90862f2e-e4a6-412f-8267-04b7f0fa3287)

Hello, why do you think I might be getting this error? I think it has nothing to do with my codes.

**Comment by jvcss** [comment]
I remember to see that, it's because the function we call in the hook is a wrapper, you should change that as I show in this video [Create a Standalone Executable from Your Streamlit App with PyInstaller 2024 UPDATE](https://youtu.be/rMvrmBJmahE)

You also can see me through the whole thoght process to update this solution in the live [Create a Standalone Executable from Your Streamlit App with PyInstaller](https://youtube.com/live/hUSrqpcxixs?feature=share)

Here in this source I don't share a whole new Streamlit framework, just this workaround that indeed need change your Streamlit source code with the newest version I've tested.

**Comment by bilaleknc** [comment]
It worked, thank you 😊
